#!/usr/bin/env python2
from hermes_python.hermes import Hermes
import sys
sys.path.append('/srv/homeassistant/lib/python3.5/site-packages')
import homeassistant.remote as remote

api = remote.API('127.0.0.1', '12345678')
presenter_name = remote.get_state(api, 'input_select.presenter_name')

def intent_received(hermes, intent_message):
    print('Intent {}'.format(intent_message.intent.intent_name))
    for (slot_value, slot) in intent_message.slots.items():
        print('Slot {} -> \n\tRaw: {} \tValue: {}'.format(slot_value, slot[0].raw_value, slot[0].slot_value.value.value))

    global booked_restaurant
    global NumOfPersons
    global BookingTime
    if intent_message.intent.intent_name == 'normanchan888:Welcome' :
        global Welcome_saved_session_id
#        if intent_message.slots.booked_restaurant:
#            booked_restaurant = intent_message.slots.booked_restaurant.first().value
        Welcome_saved_session_id = intent_message.session_id
        if intent_message.slots.booked_restaurant:
            booked_restaurant = intent_message.slots.booked_restaurant.first().value
#        hermes.publish_continue_session(intent_message.session_id, "Hello there, welcome aboard the Adonis. What can I help you with?", ["normanchan888:app_weather_WeatherCondition"])
        hermes.publish_continue_session(intent_message.session_id, "Hello {}, welcome aboard the Adonis. What can I help you with?".format(presenter_name.state), ["normanchan888:app_weather_WeatherCondition"])

    elif ((intent_message.intent.intent_name == 'normanchan888:app_weather_WeatherCondition') and (intent_message.session_id == Welcome_saved_session_id)):
        hermes.publish_continue_session(intent_message.session_id, "It is sunny today and the temperature is 75 degrees. Would you like to plan a trip", ["normanchan888:app_concierge_PlanTrip"])
    elif (intent_message.intent.intent_name == 'normanchan888:app_weather_WeatherCondition') :
        hermes.publish_end_session(intent_message.session_id, "It is sunny today and the temperature is 75 degrees.")
		
    elif ((intent_message.intent.intent_name == 'normanchan888:app_concierge_PlanTrip') and (intent_message.session_id == Welcome_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "I am showing you the destinations now.")
    elif (intent_message.intent.intent_name == 'normanchan888:app_concierge_PlanTrip') :
        hermes.publish_end_session(intent_message.session_id, "I am showing you the destinations now.")

#    elif ((intent_message.intent.intent_name == 'normanchan888:BookRestaurant') and (intent_message.session_id == Welcome_saved_session_id)):
#        if intent_message.slots.BookingTime:
#            BookingTime = intent_message.slots.BookingTime.first().value
#        hermes.publish_end_session(intent_message.session_id, "I will now request a reservation at your chosen restaurant")

with Hermes("angelmaster.local:1883") as h:
    h.subscribe_intents(intent_received).start()
