#!/usr/bin/env python2
from hermes_python.hermes import Hermes
import subprocess
#import sys
#sys.path.append('/srv/homeassistant/lib/python3.5/site-packages')
#import homeassistant.remote as remote

#api = remote.API('127.0.0.1', '12345678')
#presenter_name = remote.get_state(api, 'input_select.presenter_name')

Welcome_saved_session_id = ''
OrderBeer_saved_session_id = ''
ShoppingCategory_saved_session_id = ''
app_weather_WeatherCondition_saved_session_id = ''

def intent_received(hermes, intent_message):
    print('Intent {}'.format(intent_message.intent.intent_name))
    for (slot_value, slot) in intent_message.slots.items():
        print('Slot {} -> \n\tRaw: {} \tValue: {}'.format(slot_value, slot[0].raw_value, slot[0].slot_value.value.value))

    global booked_restaurant
    global NumOfPersons
    global BookingTime
    global ordered_item
    global shopping_category
    global shopping_item
    global Welcome_saved_session_id
    global OrderBeer_saved_session_id
    global ShoppingCategory_saved_session_id
    global app_weather_WeatherCondition_saved_session_id

    
    # if intent_message.intent.intent_name == 'normanchan888:Welcome' :
       
        # Welcome_saved_session_id = intent_message.session_id
        # if intent_message.slots.booked_restaurant:
            # booked_restaurant = intent_message.slots.booked_restaurant.first().value
        # hermes.publish_continue_session(intent_message.session_id, "Hello there, welcome aboard the Adonis. What can I help you with?", ["normanchan888:app_weather_WeatherCondition", "normanchan888:CancelMultiTurn"])
#         hermes.publish_continue_session(intent_message.session_id, "Hello {}, welcome aboard the Adonis. What can I help you with?".format(presenter_name.state), ["normanchan888:app_weather_WeatherCondition"])
    if intent_message.intent.probability < 0.3:
        sent_cmd = '/usr/bin/mosquitto_pub -h localhost -t "hermes/audioServer/'+ intent_message.site_id + '/playBytes/8ewnjksdf093jb42" -f /usr/share/snips/assistant/custom_dialogue/sound/error.wav'
        subprocess.Popen(sent_cmd, shell=True)
        hermes.publish_end_session(intent_message.session_id, "")

    elif intent_message.intent.intent_name == 'normanchan888:app_weather_WeatherCondition' :
        app_weather_WeatherCondition_saved_session_id = intent_message.session_id
        hermes.publish_continue_session(intent_message.session_id, "It is sunny today and the temperature is 75 degrees. Would you like to plan a trip?", ["normanchan888:app_concierge_PlanTrip", "normanchan888:CancelMultiTurn"])

    elif intent_message.intent.intent_name == 'normanchan888:OrderBeer' :

        OrderBeer_saved_session_id = intent_message.session_id
        if intent_message.slots.item:
            ordered_item = intent_message.slots.item.first().value
        hermes.publish_continue_session(intent_message.session_id, "I have ordered you a {} from the galley. Is there anything else you want?".format(ordered_item), ["normanchan888:StartRelaxMode", "normanchan888:CancelMultiTurn"])

    elif ((intent_message.intent.intent_name == 'normanchan888:StartRelaxMode') and (intent_message.session_id == OrderBeer_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "activating relaxation mode now")

    # elif ((intent_message.intent.intent_name == 'normanchan888:app_weather_WeatherCondition') and (intent_message.session_id == Welcome_saved_session_id)):
        # hermes.publish_continue_session(intent_message.session_id, "It is sunny today and the temperature is 75 degrees. Would you like to plan a trip", ["normanchan888:app_concierge_PlanTrip", "normanchan888:CancelMultiTurn"])
        
# #   Non-Multi-Turn handling
    # elif (intent_message.intent.intent_name == 'normanchan888:app_weather_WeatherCondition') :
        # hermes.publish_end_session(intent_message.session_id, "It is sunny today and the temperature is 75 degrees.")

        
    elif ((intent_message.intent.intent_name == 'normanchan888:app_concierge_PlanTrip') and (intent_message.session_id == app_weather_WeatherCondition_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "I am showing you the destinations now.")
#   Non-Multi-Turn handling
    elif (intent_message.intent.intent_name == 'normanchan888:app_concierge_PlanTrip') :
        hermes.publish_end_session(intent_message.session_id, "I am showing you the destinations now.")


#   Shopping Multi-turn dialogue for swimsuit and sunscreen    
    elif intent_message.intent.intent_name == 'normanchan888:app_concierge_ShoppingCategory' :

        ShoppingCategory_saved_session_id = intent_message.session_id
        if intent_message.slots.shopping_category:
            shopping_category = intent_message.slots.shopping_category.first().value
        hermes.publish_continue_session(intent_message.session_id, "Here is a list of {}".format(shopping_category), ["normanchan888:app_concierge_ShoppingItem", "normanchan888:CancelMultiTurn"])
    elif ((intent_message.intent.intent_name == 'normanchan888:app_concierge_ShoppingItem') and (intent_message.session_id == ShoppingCategory_saved_session_id)):
        hermes.publish_continue_session(intent_message.session_id, "I am placing your order now. Is there anything else you need?", ["normanchan888:app_concierge_ShoppingCategory", "normanchan888:app_concierge_ShoppingItem", "normanchan888:CancelMultiTurn"])
#   Non-Multi-Turn handling
    elif (intent_message.intent.intent_name == 'normanchan888:app_concierge_ShoppingItem') :
        hermes.publish_end_session(intent_message.session_id, "I am placing your order now")

#   Handling "No Thanks" during Welcome and Order Beer multi-turn dialogues    
    elif ((intent_message.intent.intent_name == 'normanchan888:CancelMultiTurn') and (intent_message.session_id == Welcome_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "OK")
    elif ((intent_message.intent.intent_name == 'normanchan888:CancelMultiTurn') and (intent_message.session_id == app_weather_WeatherCondition_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "OK")
    elif ((intent_message.intent.intent_name == 'normanchan888:CancelMultiTurn') and (intent_message.session_id == OrderBeer_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "OK")
    elif ((intent_message.intent.intent_name == 'normanchan888:CancelMultiTurn') and (intent_message.session_id == ShoppingCategory_saved_session_id)):
        hermes.publish_end_session(intent_message.session_id, "OK")
    
#    elif ((intent_message.intent.intent_name == 'normanchan888:BookRestaurant') and (intent_message.session_id == Welcome_saved_session_id)):
#        if intent_message.slots.BookingTime:
#            BookingTime = intent_message.slots.BookingTime.first().value
#        hermes.publish_end_session(intent_message.session_id, "I will now request a reservation at your chosen restaurant")

with Hermes("angelmaster.local:1883") as h:
    h.subscribe_intents(intent_received).start()
