#!/usr/bin/env python2
from hermes_python.hermes import Hermes

def intent_received(hermes, intent_message):
    print('Intent {}'.format(intent_message.intent.intent_name))
    for (slot_value, slot) in intent_message.slots.items():
        print('Slot {} -> \n\tRaw: {} \tValue: {}'.format(slot_value, slot[0].raw_value, slot[0].slot_value.value.value))

    global booked_restaurant
    global NumOfPersons
    global BookingTime
    if intent_message.intent.intent_name == 'normanchan888:BookRestaurant' :
        global BookRestaurant_saved_session_id
        if intent_message.slots.booked_restaurant:
            booked_restaurant = intent_message.slots.booked_restaurant.first().value
        BookRestaurant_saved_session_id = intent_message.session_id
        hermes.publish_continue_session(intent_message.session_id, "For how many people", ["normanchan888:SetNumOfPersons"])

    elif ((intent_message.intent.intent_name == 'normanchan888:SetNumOfPersons') and (intent_message.session_id == BookRestaurant_saved_session_id)):
        if intent_message.slots.NumOfPersons:
            NumOfPersons = intent_message.slots.NumOfPersons.first().value
        hermes.publish_continue_session(intent_message.session_id, "For what time", ["normanchan888:SetBookingTime"])

    elif ((intent_message.intent.intent_name == 'normanchan888:SetBookingTime') and (intent_message.session_id == BookRestaurant_saved_session_id)):
        if intent_message.slots.BookingTime:
            BookingTime = intent_message.slots.BookingTime.first().value
        hermes.publish_end_session(intent_message.session_id, "I have reserved a table at {0} for a party of {1} for {2}. We are now setting sail with an estimated travel time of 3 hours.".format(booked_restaurant,int(NumOfPersons),BookingTime.split(' ')[1][:5])))

with Hermes("angelmaster.local:1883") as h:
    h.subscribe_intents(intent_received).start()
